#
# Definition of all trackable objects
# Identifier corresponds to Streaming ID set in Motive
#
mocap_node:
    ros__parameters:
        rigid_bodies:
            '4':
                pose: DiamondBase/pose
                pose2d: DiamondBase/pose2d
                odom: DiamondBase/odom
                tf: tf
                child_frame_id: DiamondBase/base_link
                parent_frame_id: world
        free_markers: true # set to true to publish marker positions for markers not in rigid bodies
        optitrack_config:
                # should match the Multicast Interface in Motive streaming panel
                multicast_address: 239.255.42.99
                command_port: 1510
                data_port: 1511
                enable_optitrack: true
